services:
  - type: web
    name: teyvat-atlas
    runtime: static
    branch: main
    autoDeploy: true
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
