import { Link } from 'react-router-dom';
import { ArrowRight, BookOpen, Boxes, Compass, Gem, Map, Swords, Users } from 'lucide-react';
import { SectionTitle } from '../components/SectionTitle';
import { useCharacters } from '../hooks/useCharacters';

export function DashboardPage() {
  const { allCharacters, loading } = useCharacters('');
  const favorites = allCharacters.filter((character) => localStorage.getItem(`favorite:${character.id}`) === '1').slice(0, 6);
  return <div>
    <section className="hero-card"><div className="hero-copy"><div className="eyebrow">TEYVAT ATLAS · LIVE LIBRARY</div><h1>A single workspace for characters, builds, materials, teams and exploration.</h1><p>Game data is fetched from public structured providers, images are resolved separately, and player tools stay local. Character pages clearly separate live facts from curated build advice.</p><div className="hero-actions"><Link to="/characters" className="button primary">Browse characters <ArrowRight size={15} /></Link><Link to="/teams" className="button secondary">Build a team</Link></div><div className="hero-stats"><div><strong>{loading ? '—' : allCharacters.length}</strong><span>characters indexed</span></div><div><strong>3+</strong><span>data providers</span></div><div><strong>0</strong><span>backend accounts</span></div></div></div><div className="hero-rings"><span /><span /><span /><strong>ATLAS</strong><small>Live sources<br />Local progress</small></div></section>
    <section className="section-block"><SectionTitle eyebrow="TOOLKIT" title="Everything in one library" /><div className="feature-grid six"><Link to="/characters" className="feature-card"><Users /><h3>Characters</h3><p>Search every indexed playable character and open a unified data page.</p></Link><Link to="/weapons" className="feature-card"><Swords /><h3>Weapons</h3><p>Live weapon index with rarity, type and source data.</p></Link><Link to="/artifacts" className="feature-card"><Boxes /><h3>Artifacts</h3><p>Browse sets from the same structured database layer.</p></Link><Link to="/materials" className="feature-card"><Gem /><h3>Material Planner</h3><p>Aggregate material objects for the characters you select.</p></Link><Link to="/teams" className="feature-card"><BookOpen /><h3>Team Builder</h3><p>Assemble and save four-character teams locally.</p></Link><Link to="/map" className="feature-card"><Map /><h3>Map & Tracker</h3><p>Open full community map coverage plus local progress tools.</p></Link></div></section>
    <section className="section-block two-up"><section className="panel"><SectionTitle eyebrow="FAVORITES" title="Saved characters" />{favorites.length ? <div className="mini-character-list">{favorites.map((character) => <Link to={`/characters/${encodeURIComponent(character.id)}`} key={character.id}>{character.name}<span>{character.element} · {character.weapon}</span></Link>)}</div> : <div className="empty-state">Save characters from their detail pages and they will appear here.</div>}</section><section className="panel"><SectionTitle eyebrow="SOURCE HEALTH" title="How the app stays accurate" /><div className="health-list"><div><Compass size={15} /><span>Structured game data</span><strong>GenshinDB</strong></div><div><Compass size={15} /><span>Entity images</span><strong>genshin.dev</strong></div><div><Compass size={15} /><span>Public build lookup</span><strong>Enka.Network</strong></div></div></section></section>
    <section className="callout"><div><div className="eyebrow">TRANSPARENCY</div><h3>Facts are not disguised as “meta rankings.”</h3><p>Live game data is shown as data. Build opinions are labeled as curated or external references, so the app does not silently turn one site's preferences into universal truth.</p></div><Link className="button secondary" to="/sources">See every source</Link></section>
  </div>;
}
